name: 'Deploy with kustomize'
description: 'This action compiles your kustomize manifests and deploys it with kubectl'
inputs:
  registry:
    description: 'Registry to the docker images'
    required: false
  images:
    description: 'The images to edit to a new image version. Note its currently hardcoded to change from :latest to a version you provide'
    required: false
  overlay:
    description: 'The path to the overlay to kustomize'
    required: true
  monitoring:
    description: 'Enables kubectl rollout checks on all Deployments, stateful-sets and daemons within the compiled manifest'
    required: false
  kustomize:
    description: 'The version of kustomize to use'
    required: true
    default: '5.3.0'
  kubectl:
    description: 'The version of kubectl to use'
    required: true
    default: '1.23.6'
  namesuffix:
    description: 'Add suffix to all resources'
    required: false
    default: ''
runs:
  using: 'node20'
  main: 'dist/index.js'
